### ISSUE TITLE
对 webpack 不熟悉，hey dev 报错

### ISSUE THREAD

**Issue by foreverZ133** [heyui/hey-cli#4]
package.json 里面有配置：
![tim 20180306162648](https://user-images.githubusercontent.com/22021589/37021669-4ba2806c-215b-11e8-9274-2c7f0d693bc9.jpg)
文件夹里也有 hey.js
![tim 20180306162703](https://user-images.githubusercontent.com/22021589/37021671-4bdc8140-215b-11e8-993f-273965158e34.jpg)
但报错说没找到 module
![tim 20180306162731](https://user-images.githubusercontent.com/22021589/37021672-4c186d36-215b-11e8-8d18-dd731d960a19.jpg)

**Comment by foreverZ133** [comment]
我的错，init 后文件目录还得 cd 一下。

**Comment by vvpvvp** [comment]
新版本的配置已经不推荐在package.json中配置了，请在test目录下面的hey.js中进行配置。
