### ISSUE TITLE
hey dev 确认后弹出了 sublime，是让我改 hey.js 吗

### ISSUE THREAD

**Issue by foreverZ133** [heyui/hey-cli#5]
安装都正常，文件也没动。

然后 cmd 里输入 hey dev 回车，
结果打开了我的 sublime text，并打开了 hey.js 文件。
然后就没有然后了。

这是怎么回事呀，是要我卸载 sublime 或者修改 hey.js 吗？

**Comment by vvpvvp** [comment]
请补充一下操作系统的信息以及npm的一些信息可以吗？

**Comment by foreverZ133** [comment]
node，npm，hei-cli 的版本：
![tim 20180307130308](https://user-images.githubusercontent.com/22021589/37074476-032ed24c-2208-11e8-875d-22faf976d5d5.jpg)
电脑系统 win10：
![tim 20180307130338](https://user-images.githubusercontent.com/22021589/37074477-036e3202-2208-11e8-9669-a6e03bbebe58.jpg)
sublime 下载的破解版：
![tim 20180307130352](https://user-images.githubusercontent.com/22021589/37074478-03af32a2-2208-11e8-94f9-00226bafd3de.jpg)

**Comment by vvpvvp** [comment]
感谢你的支持，我们会按照这个环境来测试一遍。

**Comment by vvpvvp** [comment]
已修复。
bug原因：Win10下使用hey命令执行的时候，会自动打开hey.js文件，命令匹配逻辑第一逻辑是当前目录下的对应文件，hey命令与hey.js文件命名重复。
修复：新版本的hey-cli使用hey.conf.js文件作为配置文件。

建议执行：
```
npm uninstall -g hey-cli
npm install -g hey-cli@1.2.2
```

**Comment by qindeng** [comment]
加什么属性才不会自动打开浏览器

**Comment by vvpvvp** [comment]
自动打开浏览器不好吗？

**Comment by vvpvvp** [comment]
第一次开启，没有打开页面呢？自己输入不是更加麻烦？

**Comment by qindeng** [comment]
你就说有没有不自动打开浏览器的属性嘛，

**Comment by vvpvvp** [comment]
没有

**Comment by qindeng** [comment]
那我只能改你的源码自己加咯

**Comment by vvpvvp** [comment]
请更新版本，已经加好了。
![image](https://user-images.githubusercontent.com/7303371/56266366-99dfb980-611e-11e9-9a9e-8641f16e8729.png)

**Comment by qindeng** [comment]
好的

**Comment by qindeng** [comment]
还问你一个问题，怎么配置指定JS不被编译

**Comment by qindeng** [comment]
![image](https://user-images.githubusercontent.com/39475798/56274480-5fcbe300-6131-11e9-8b68-0fc050d5aa6e.png) 这个是vue-cli的代码

**Comment by vvpvvp** [comment]
暂时没有这个功能，原则上，src内的都会编辑。
