### ISSUE TITLE
[New Feature] Add HeyAdmin template into hey-cli

### ISSUE THREAD

**Issue by kongyajie** [heyui/hey-cli#8]
As I start a new heyAdmin project via hey-cli, naturally I expect to see a heyAdmin template option.
 
But the fact is NO, and I have to refer to https://heyui.github.io/heyui-admin-docs/#start and copy the commands to do so. 

Appreciate if you can add heyAdmin template into hey-cli, many thanks :p

**Comment by vvpvvp** [comment]
It would be better if you could RP directly.

**Comment by vvpvvp** [comment]
https://github.com/heyui/hey-cli-template
